version: '3'

tasks:
  build:
    silent: true
    cmds:
      - xcodebuild -project ./NyaIME.xcodeproj -configuration Debug
  install:
    silent: true
    deps: [build]
    cmds:
      - cp -R ./build/Debug/NyaIME.app ~/Library/Input\ Methods
